(() => {
  const config = window.TRIAGE_APP_CONFIG;
  if (!config) return;

  const extraSignals = {
    chills: ["chills", "rigors", "kapkapi", "thand lagna"],
    highFever: ["high fever", "104", "103", "very high temperature"],
    lowFever: ["low grade fever", "mild fever"],
    nightSweats: ["night sweats", "raat ko pasina"],
    weightLoss: ["weight loss", "wazan kam"],
    appetiteLoss: ["loss of appetite", "bhook kam"],
    fatigue: ["fatigue", "tired", "thakan"],
    runnyNose: ["runny nose", "blocked nose", "naak behna", "sardi"],
    sneezing: ["sneezing", "chheenk"],
    earPain: ["ear pain", "kaan dard"],
    hearingLoss: ["hearing loss", "sunai kam"],
    sinusPain: ["sinus", "facial pain", "chehre mein dard"],
    eyeRedness: ["red eye", "eye redness", "aankh lal"],
    visionBlur: ["blurred vision", "vision loss", "dhundla dikhna"],
    palpitations: ["palpitation", "heart racing", "dhadkan"],
    swellingLegs: ["leg swelling", "pair sujan", "ankle swelling"],
    flankPain: ["flank pain", "side pain", "back side pain"],
    bloodUrine: ["blood in urine", "hematuria", "urine mein blood"],
    pelvicPain: ["pelvic pain", "lower abdomen pain"],
    vaginalBleeding: ["vaginal bleeding", "bleeding in pregnancy"],
    missedPeriod: ["missed period", "period late"],
    menstrualPain: ["period pain", "menstrual cramps"],
    heavyBleeding: ["heavy periods", "heavy bleeding"],
    itching: ["itching", "khujli"],
    skinLesion: ["skin lesion", "patch", "fungal", "ringworm"],
    pus: ["pus", "peep"],
    swelling: ["swelling", "sujan"],
    injury: ["injury", "fall", "chot"],
    backPain: ["back pain", "kamar dard"],
    neckPain: ["neck pain", "gardan dard"],
    numbness: ["numbness", "tingling", "sunn"],
    seizure: ["seizure", "fits", "daura"],
    confusion: ["confusion", "behaviour change", "behoshi"],
    anxiety: ["anxiety", "panic", "ghabrahat"],
    lowMood: ["low mood", "depression", "sadness"],
    insomnia: ["sleep problem", "insomnia", "neend nahi"],
    highBp: ["high bp", "blood pressure", "hypertension"],
    lowSugar: ["low sugar", "hypoglycemia", "sweating with hunger"],
    sweating: ["sweating", "pasina", "cold sweat"],
    thirst: ["excessive thirst", "pyaas", "polydipsia"],
    weightGain: ["weight gain", "wazan badhna"],
    coldIntolerance: ["cold intolerance", "cold lagna"],
    heatIntolerance: ["heat intolerance", "garmi lagna"],
    jaundice: ["yellow eyes", "jaundice", "peelia"],
    blackStool: ["black stool", "melena", "kala stool"],
    bloodStool: ["blood in stool", "stool mein blood"],
    constipation: ["constipation", "kabz"],
    acidity: ["acidity", "heartburn", "gastric"],
    severePain: ["severe pain", "bahut dard"],
    mosquitoExposure: ["mosquito", "dengue area", "malaria area"],
    wheezing: ["wheezing", "seeti wali saans", "wheeze"],
  };

  const extraItems = [
    ["Common cold / allergic rhinitis", "ENT Specialist", ["runnyNose", "sneezing", "cough", "soreThroat"], ["Is fever present or only sneezing/runny nose?", "Any seasonal allergy, dust exposure, or wheezing?", "Any facial pain or thick nasal discharge?"], "ENT/physician review if symptoms persist, fever is high, or breathing difficulty appears."],
    ["Acute pharyngitis / tonsillitis", "ENT Specialist", ["soreThroat", "fever", "headache", "weakness"], ["Is swallowing painful?", "Any pus on tonsils or swollen neck nodes?", "Any cough or runny nose?"], "ENT or physician review for severe throat pain, fever, or inability to swallow."],
    ["Acute sinusitis", "ENT Specialist", ["sinusPain", "runnyNose", "headache", "fever"], ["How many days has nasal blockage continued?", "Is facial pain worse on bending?", "Is discharge thick or foul smelling?"], "ENT review if symptoms last beyond 10 days or worsen after initial improvement."],
    ["Otitis media / ear infection", "ENT Specialist", ["earPain", "fever", "hearingLoss"], ["Is there ear discharge?", "Any recent cold or throat infection?", "Is hearing reduced?"], "ENT review, especially for children, discharge, severe pain, or hearing loss."],
    ["Conjunctivitis", "Ophthalmologist", ["eyeRedness", "itching", "runnyNose"], ["Is there sticky discharge?", "Is vision blurred or painful?", "Any contact lens use?"], "Eye review urgently if pain, vision change, injury, or contact lens use is present."],
    ["Migraine / recurrent headache", "Neurologist", ["headache", "vomiting", "visionBlur"], ["Is headache one-sided or pulsating?", "Any light sensitivity or vomiting?", "Any new weakness, seizure, or worst-ever headache?"], "Neurology/physician review for recurrent migraine; emergency for red flags."],
    ["Tension-type headache", "Neurologist", ["headache", "neckPain", "anxiety"], ["Is pain band-like or stress related?", "Any fever, vomiting, or neurologic symptoms?", "How often does it occur?"], "Physician/neurology review if frequent, severe, or new pattern."],
    ["Stroke warning / TIA possibility", "Emergency / Triage Desk", ["confusion", "numbness", "visionBlur", "weakness"], ["Any face droop, arm weakness, or speech difficulty?", "When did symptoms start?", "Any diabetes, BP, or heart disease?"], "Emergency evaluation immediately for sudden neurologic deficit."],
    ["Seizure episode", "Neurologist", ["seizure", "confusion", "headache"], ["Was there loss of consciousness?", "How long did the episode last?", "Any fever, head injury, pregnancy, or diabetes?"], "Emergency/neurology review after first seizure or prolonged seizure."],
    ["Anxiety / panic symptoms", "Psychiatrist", ["anxiety", "palpitations", "breathlessness", "dizziness"], ["Are episodes sudden and recurrent?", "Any chest pain or fainting?", "Any major stressor or substance use?"], "Rule out medical causes first; psychiatry/physician review if recurrent."],
    ["Depression / low mood concern", "Psychiatrist", ["lowMood", "insomnia", "fatigue", "appetiteLoss"], ["How long has low mood persisted?", "Any loss of interest, hopelessness, or self-harm thoughts?", "Any substance use?"], "Mental health review; urgent support for self-harm thoughts."],
    ["Insomnia / sleep disorder", "Psychiatrist", ["insomnia", "anxiety", "fatigue"], ["How many nights per week is sleep affected?", "Any snoring, alcohol, caffeine, or screen use?", "Any anxiety or low mood?"], "Physician/psychiatry review if persistent or functionally impairing."],
    ["Hypertension / high blood pressure concern", "Cardiologist", ["highBp", "headache", "dizziness", "chestPain"], ["What BP reading was recorded and when?", "Any chest pain, breathlessness, weakness, or vision symptoms?", "Any BP medicines missed?"], "Cardiology/physician review; emergency for severe symptoms or very high BP."],
    ["Stable angina / cardiac chest pain possibility", "Cardiologist", ["chestPain", "breathlessness", "palpitations"], ["Is pain triggered by exertion and relieved by rest?", "Any sweating, nausea, or left arm/jaw pain?", "Any diabetes, BP, smoking, or prior heart disease?"], "Urgent cardiac evaluation for chest pain, especially with sweating or breathlessness."],
    ["Heart failure / fluid overload possibility", "Cardiologist", ["breathlessness", "swellingLegs", "fatigue"], ["Is breathlessness worse lying down?", "Any leg swelling or sudden weight gain?", "Known heart/kidney disease?"], "Cardiology/physician review; emergency for severe breathlessness."],
    ["Asthma flare", "Pulmonologist / Chest Physician", ["breathlessness", "cough", "wheezing", "chestPain"], ["Is wheezing present?", "Any inhaler use or previous asthma?", "Is speaking difficult or oxygen low?"], "Pulmonology review; emergency for severe breathlessness or low oxygen."],
    ["COPD exacerbation", "Pulmonologist / Chest Physician", ["cough", "breathlessness", "fever", "fatigue"], ["Any smoking/COPD history?", "Is sputum increased or changed color?", "Any oxygen drop?"], "Pulmonology review; emergency for respiratory distress."],
    ["Pneumonia possibility", "Pulmonologist / Chest Physician", ["fever", "cough", "breathlessness", "chestPain"], ["How many days of fever and cough?", "Any fast breathing, chest pain, or low oxygen?", "Age above 60 or chronic disease?"], "Physician/pulmonology review; urgent care for breathing difficulty."],
    ["Tuberculosis possibility", "Pulmonologist / Chest Physician", ["cough", "weightLoss", "nightSweats", "fever"], ["Has cough lasted more than 2 weeks?", "Any blood in sputum, night sweats, or weight loss?", "Any TB contact?"], "Chest physician review and appropriate TB testing as advised."],
    ["COVID-like viral respiratory illness", "General Physician / Internal Medicine", ["fever", "cough", "soreThroat", "bodyAche"], ["Any exposure or positive test?", "Any breathlessness or oxygen drop?", "Any elderly/pregnancy/diabetes risk?"], "Physician review if high risk, worsening, or breathing difficulty."],
    ["Malaria possibility", "General Physician / Internal Medicine", ["fever", "chills", "mosquitoExposure", "headache"], ["Is fever intermittent with chills?", "Any travel or mosquito exposure?", "Any vomiting, jaundice, or confusion?"], "Physician review and malaria testing where clinically indicated."],
    ["Dengue fever possibility", "General Physician / Internal Medicine", ["fever", "bodyAche", "jointPain", "rash", "mosquitoExposure"], ["Any severe body pain, rash, bleeding, or abdominal pain?", "Any dengue cases nearby?", "Has CBC/platelet count been done?"], "Physician review; avoid unsupervised NSAIDs and monitor red flags."],
    ["Chikungunya possibility", "General Physician / Internal Medicine", ["fever", "jointPain", "rash", "bodyAche"], ["Is joint pain severe or persistent?", "Any rash or mosquito exposure?", "Any swelling of small joints?"], "Physician review, especially for elderly or persistent joint symptoms."],
    ["Typhoid / enteric fever possibility", "General Physician / Internal Medicine", ["fever", "abdominalPain", "diarrhea", "appetiteLoss"], ["How many days has fever continued?", "Any abdominal pain, constipation/diarrhea, or travel food exposure?", "Any tests already done?"], "Physician review for persistent fever beyond 3-5 days."],
    ["Acute gastroenteritis", "Gastroenterologist / General Physician", ["vomiting", "diarrhea", "abdominalPain", "fever"], ["How many stools/vomits in 24 hours?", "Any blood in stool or dehydration?", "Any outside food or contaminated water?"], "Assess dehydration; urgent care for blood, dehydration, infants, elderly, pregnancy."],
    ["GERD / acidity", "Gastroenterologist / General Physician", ["acidity", "chestPain", "abdominalPain"], ["Is burning after meals or lying down?", "Any weight loss, vomiting blood, black stool, or difficulty swallowing?", "Any pain with exertion?"], "Physician review; emergency if cardiac symptoms cannot be excluded."],
    ["Peptic ulcer / gastritis possibility", "Gastroenterologist / General Physician", ["abdominalPain", "acidity", "blackStool", "vomiting"], ["Is pain related to meals?", "Any black stool, vomiting blood, or NSAID use?", "Any weight loss?"], "Gastro/physician review; urgent for bleeding symptoms."],
    ["Appendicitis possibility", "Emergency / Triage Desk", ["abdominalPain", "fever", "vomiting", "severePain"], ["Is pain moving to right lower abdomen?", "Any fever or vomiting?", "Is walking/coughing painful?"], "Emergency/surgical review if appendicitis symptoms are suspected."],
    ["Gallbladder disease possibility", "Gastroenterologist / General Physician", ["abdominalPain", "vomiting", "jaundice"], ["Is pain in right upper abdomen after fatty food?", "Any fever or yellow eyes?", "Any prior stones?"], "Gastro/surgical review; urgent if fever or jaundice."],
    ["Hepatitis / jaundice concern", "Gastroenterologist / General Physician", ["jaundice", "fatigue", "vomiting", "abdominalPain"], ["When did yellow eyes/urine start?", "Any fever, alcohol, medicines, or contaminated food?", "Any abdominal swelling or confusion?"], "Physician/gastro review for jaundice and liver tests."],
    ["Constipation", "Gastroenterologist / General Physician", ["constipation", "abdominalPain"], ["How many days without stool?", "Any vomiting, abdominal swelling, blood, or weight loss?", "Any new medicines?"], "Physician review if severe, persistent, or red flags."],
    ["Urinary tract infection", "Urologist / General Physician", ["burningUrine", "fever", "abdominalPain", "weakness"], ["Any frequency, urgency, or lower abdominal pain?", "Any fever with chills or back pain?", "Pregnant, diabetic, elderly, or recurrent UTI?"], "Urinalysis and clinician review; urgent for fever/flank pain/pregnancy."],
    ["Kidney stone / renal colic", "Urologist / General Physician", ["flankPain", "bloodUrine", "vomiting", "severePain"], ["Is pain colicky from back to groin?", "Any blood in urine or vomiting?", "Any fever or single kidney?"], "Urology/urgent review; fever with stone symptoms is urgent."],
    ["Acute urinary retention", "Urologist / General Physician", ["abdominalPain", "burningUrine", "severePain"], ["Unable to pass urine?", "Any lower abdominal swelling?", "Any prostate history or medicines?"], "Urgent urology/emergency care if unable to pass urine."],
    ["Chronic kidney disease concern", "Nephrologist", ["swellingLegs", "fatigue", "highBp", "weakness"], ["Known kidney disease or abnormal creatinine?", "Any swelling, reduced urine, or high BP?", "Any diabetes/hypertension history?"], "Nephrology/physician review with renal function tests."],
    ["Diabetes / hyperglycemia concern", "Endocrinologist / Diabetologist", ["highSugar", "thirst", "weakness", "weightLoss"], ["What was the latest sugar reading?", "Any excessive thirst, urination, weight loss?", "Any vomiting, confusion, or rapid breathing?"], "Diabetologist/physician review; emergency for confusion/vomiting with high sugar."],
    ["Hypoglycemia / low sugar concern", "Emergency / Triage Desk", ["lowSugar", "dizziness", "sweating", "confusion"], ["What glucose reading was recorded?", "Any insulin/tablet overdose or missed meal?", "Is the patient conscious and able to swallow?"], "Urgent care if unconscious, confused, seizure, or recurrent low sugar."],
    ["Hypothyroidism possibility", "Endocrinologist / Diabetologist", ["fatigue", "weightGain", "coldIntolerance", "constipation"], ["Any weight gain, constipation, cold intolerance?", "Any neck swelling or thyroid history?", "Any pregnancy/postpartum state?"], "Endocrinology/physician review with thyroid testing if appropriate."],
    ["Hyperthyroidism possibility", "Endocrinologist / Diabetologist", ["palpitations", "weightLoss", "heatIntolerance", "anxiety"], ["Any tremor, palpitations, weight loss?", "Any neck swelling or eye symptoms?", "Any pregnancy/postpartum state?"], "Endocrinology/physician review with thyroid testing if appropriate."],
    ["Anemia possibility", "General Physician / Internal Medicine", ["fatigue", "dizziness", "breathlessness", "weakness"], ["Any heavy periods, poor diet, black stool, or pregnancy?", "Any palpitations or breathlessness on exertion?", "Any CBC/hemoglobin report?"], "Physician review and CBC/iron/B12 evaluation as advised."],
    ["Skin fungal infection", "Dermatologist", ["itching", "skinLesion", "rash"], ["Is rash ring-shaped or itchy?", "Any groin/feet involvement?", "Any steroid cream use?"], "Dermatology review if spreading, recurrent, or face/genital involvement."],
    ["Eczema / dermatitis", "Dermatologist", ["rash", "itching", "skinLesion"], ["Any dry itchy patches?", "Any new soap/cosmetic/chemical exposure?", "Any oozing or infection?"], "Dermatology review for persistent or infected rash."],
    ["Cellulitis / skin infection", "Dermatologist", ["swelling", "pus", "fever", "severePain"], ["Is skin red, hot, painful, or spreading?", "Any pus, diabetes, or fever?", "Any injury or bite?"], "Urgent physician/dermatology review for spreading infection or fever."],
    ["Acne / folliculitis", "Dermatologist", ["skinLesion", "pus"], ["Are lesions on face/back/chest?", "Any painful boils or scarring?", "Any cosmetic/steroid use?"], "Dermatology review if severe, painful, or scarring."],
    ["Back strain / mechanical back pain", "Orthopedist", ["backPain", "injury", "severePain"], ["Any injury or lifting trigger?", "Any leg numbness/weakness?", "Any bladder/bowel symptoms or fever?"], "Orthopedic/physician review; emergency for neurologic or bladder/bowel symptoms."],
    ["Sciatica / nerve root pain", "Orthopedist", ["backPain", "numbness", "severePain"], ["Does pain travel down the leg?", "Any numbness or weakness?", "Any bladder/bowel control problem?"], "Orthopedics/neurology review; emergency for weakness or bladder/bowel symptoms."],
    ["Arthritis / inflammatory joint pain", "Rheumatologist", ["jointPain", "swelling", "fatigue"], ["Is morning stiffness more than 30 minutes?", "Any multiple swollen joints?", "Any fever/rash/weight loss?"], "Rheumatology/physician review if persistent swelling or inflammatory pattern."],
    ["Sprain / minor injury", "Orthopedist", ["injury", "swelling", "jointPain"], ["Was there fall/twist?", "Can the patient bear weight?", "Any deformity or severe swelling?"], "Orthopedic review/X-ray if severe pain, deformity, or inability to bear weight."],
    ["Pregnancy with acute symptoms", "Obstetrician / Gynecologist", ["pregnancy", "abdominalPain", "vaginalBleeding", "vomiting"], ["How many weeks pregnant?", "Any bleeding, severe pain, fever, or reduced fetal movement?", "Any BP, diabetes, or prior complications?"], "OB/GYN or emergency review for bleeding, severe pain, high BP symptoms, or reduced fetal movement."],
    ["Heavy menstrual bleeding", "Obstetrician / Gynecologist", ["heavyBleeding", "weakness", "dizziness"], ["How many pads per day?", "Any clots, pregnancy possibility, or dizziness?", "Any known fibroids or anemia?"], "Gynecology review; urgent if soaking pads rapidly or fainting."],
    ["PCOS / irregular periods possibility", "Obstetrician / Gynecologist", ["missedPeriod", "weightGain", "skinLesion"], ["How irregular are cycles?", "Any acne, hair growth, weight gain?", "Any pregnancy possibility?"], "Gynecology/endocrine review for persistent irregular cycles."],
  ];

  Object.assign(config.signals, extraSignals);
  const existing = new Set((config.items || []).map((item) => item.name));
  const newItems = extraItems
    .filter(([name]) => !existing.has(name))
    .map(([name, route, match, questions, nextStep]) => ({ name, route, match, questions, nextStep }));
  config.items = [...(config.items || []), ...newItems];
  config.seedMetadata = {
    diseaseRecordCount: config.items.length,
    sourceNote: "Condition/routing seed topics are aligned to common OPD workflows and ICMR Standard Treatment Workflow topic coverage. They are triage support records, not diagnosis or treatment instructions.",
  };
})();
