window.TRIAGE_APP_CONFIG = {
  appName: "Axnovus Care Agent",
  defaultPatient: {
    age: 32,
    sex: "Male",
    location: "Delhi, India",
  },
  languageHints: ["en-IN", "hi-IN"],
  llm: {
    endpoint: "/api/triage",
    primary: true,
    defaultModel: "gpt-4.1",
    models: [
      { id: "gpt-4.1", label: "Comprehensive review" },
      { id: "gpt-4.1-mini", label: "Balanced review" },
      { id: "gpt-4o-mini", label: "Fast review" },
    ],
    task: "india_healthcare_symptom_triage",
    safetyInstruction:
      "Return possible conditions, follow-up questions, red flags, and specialist routing. Do not diagnose, prescribe, or replace a clinician.",
  },
  feedback: {
    storageKey: "axnovus-care-agent-feedback-v1",
    minimumApprovedCasesForLocalUse: 25,
  },
  quickInputs: [
    "Fever / bukhar",
    "Cough / khansi",
    "Breathlessness / saans phoolna",
    "Headache / sir dard",
    "Vomiting / ulti",
    "Loose motion / dast",
    "Burning urine / peshab mein jalan",
    "Rash / daane",
    "Joint pain / jodon mein dard",
  ],
  signals: {
    fever: ["fever", "bukhar", "\u092c\u0941\u0916\u093e\u0930", "temperature"],
    cough: ["cough", "khansi", "\u0916\u093e\u0902\u0938\u0940"],
    breathlessness: ["breathless", "breathing", "saans", "\u0938\u093e\u0902\u0938", "\u0938\u093e\u0901\u0938", "dum"],
    chestPain: ["chest pain", "seene mein dard", "\u0938\u0940\u0928\u0947 \u092e\u0947\u0902 \u0926\u0930\u094d\u0926", "chhati", "\u091b\u093e\u0924\u0940"],
    headache: ["headache", "sir dard", "\u0938\u093f\u0930 \u0926\u0930\u094d\u0926", "\u0938\u0930 \u0926\u0930\u094d\u0926"],
    bodyAche: ["body pain", "body ache", "badan dard", "\u092c\u0926\u0928 \u0926\u0930\u094d\u0926", "\u0936\u0930\u0940\u0930 \u0926\u0930\u094d\u0926"],
    soreThroat: ["throat", "gala", "\u0917\u0932\u093e", "sore throat"],
    rash: ["rash", "daane", "\u0926\u093e\u0928\u0947", "\u091a\u0915\u0924\u094d\u0924\u0947"],
    vomiting: ["vomit", "vomiting", "ulti", "\u0909\u0932\u094d\u091f\u0940"],
    diarrhea: ["diarrhea", "loose motion", "dast", "\u0926\u0938\u094d\u0924"],
    abdominalPain: ["stomach pain", "abdominal", "pet dard", "\u092a\u0947\u091f \u0926\u0930\u094d\u0926"],
    burningUrine: ["burning urine", "urine burn", "peshab mein jalan", "\u092a\u0947\u0936\u093e\u092c \u092e\u0947\u0902 \u091c\u0932\u0928"],
    jointPain: ["joint pain", "jodon mein dard", "\u091c\u094b\u0921\u093c\u094b\u0902 \u092e\u0947\u0902 \u0926\u0930\u094d\u0926"],
    weakness: ["weakness", "kamzori", "\u0915\u092e\u091c\u094b\u0930\u0940", "thakan", "\u0925\u0915\u093e\u0928"],
    dizziness: ["dizziness", "chakkar", "\u091a\u0915\u094d\u0915\u0930"],
    highSugar: ["sugar", "diabetes", "madhumeh", "\u092e\u0927\u0941\u092e\u0947\u0939"],
    pregnancy: ["pregnant", "pregnancy", "garbhavati", "\u0917\u0930\u094d\u092d\u0935\u0924\u0940"],
  },
  items: [
    {
      name: "Viral fever / influenza-like illness",
      route: "General Physician / Internal Medicine",
      match: ["fever", "cough", "bodyAche", "soreThroat", "headache"],
      questions: [
        "How many days has the fever been present, and what was the highest temperature?",
        "Is there cough, sore throat, blocked nose, or body pain?",
        "Has anyone at home, school, or office had similar symptoms?",
      ],
      nextStep: "OPD physician review if fever persists beyond 3 days, worsens, or the patient is elderly, pregnant, diabetic, or immunocompromised.",
    },
    {
      name: "Dengue / chikungunya possibility",
      route: "General Physician / Internal Medicine",
      match: ["fever", "bodyAche", "jointPain", "rash", "headache"],
      questions: [
        "Is there severe body pain, joint pain, rash, bleeding gums, or black stools?",
        "Is dengue currently common in your area, or has there been mosquito exposure?",
        "Has a CBC platelet count or dengue test already been done?",
      ],
      nextStep: "Recommend physician review and CBC/platelet assessment; avoid self-medicating with NSAIDs unless a clinician advises.",
    },
    {
      name: "Respiratory infection / asthma-COPD flare",
      route: "Pulmonologist / Chest Physician",
      match: ["cough", "breathlessness", "fever", "soreThroat"],
      questions: [
        "Is breathing difficulty present at rest or only while walking?",
        "Is there wheezing, chest tightness, oxygen drop, or blue lips?",
        "Any history of asthma, COPD, smoking, TB, or recent COVID exposure?",
      ],
      nextStep: "Route to pulmonology or emergency care depending on oxygen level, chest pain, or severe breathlessness.",
    },
    {
      name: "Gastroenteritis / food-borne illness",
      route: "Gastroenterologist / General Physician",
      match: ["vomiting", "diarrhea", "abdominalPain", "fever", "weakness"],
      questions: [
        "How many loose stools or vomiting episodes occurred in the last 24 hours?",
        "Is there blood in stool, severe dehydration, or inability to drink fluids?",
        "Did symptoms start after outside food, travel, or contaminated water?",
      ],
      nextStep: "Assess dehydration risk; route children, elderly patients, pregnancy, and blood in stool for urgent care.",
    },
    {
      name: "Urinary tract infection",
      route: "Urologist / General Physician",
      match: ["burningUrine", "fever", "abdominalPain", "weakness"],
      questions: [
        "Is there burning urine, increased frequency, lower abdominal pain, or back pain?",
        "Is fever with chills present?",
        "Is the patient pregnant, diabetic, elderly, or having recurrent UTIs?",
      ],
      nextStep: "Recommend urinalysis and clinician review; pregnancy, high fever, or flank pain needs faster escalation.",
    },
    {
      name: "Diabetes complication / metabolic concern",
      route: "Endocrinologist / Diabetologist",
      match: ["highSugar", "weakness", "dizziness", "vomiting"],
      questions: [
        "What was the latest blood sugar reading and when was it measured?",
        "Is there excessive thirst, frequent urination, vomiting, confusion, or rapid breathing?",
        "Which diabetes medicines or insulin doses are currently being taken?",
      ],
      nextStep: "Route to diabetologist; confusion, vomiting with high sugar, or very low sugar symptoms need emergency evaluation.",
    },
  ],
  urgencyRules: [
    { key: "chestPain", text: "Chest pain can indicate a cardiac emergency." },
    { key: "breathlessness", text: "Severe breathing difficulty needs urgent evaluation." },
    { key: "pregnancy", text: "Pregnancy with acute symptoms should be triaged with extra caution." },
  ],
};
